### ISSUE TITLE
Refactor codebase structure

### ISSUE THREAD

**Issue by devdave25** [cr1pto/simple_bible#13]
We should change the structure slightly so that we have screens that we are using and add a folder for dumb components.

**Comment by cr1pto** [comment]
I like this idea. Let's do it.

**Comment by devdave25** [comment]
This should be improved a bit on this PR - https://github.com/cr1pto/simple_bible/pull/14

**Comment by cr1pto** [comment]
The codebase has been dramatically changed - let's revisit this if it's a problem
