### ISSUE TITLE
Build a home page

### ISSUE THREAD

**Issue by devdave25** [cr1pto/simple_bible#17]
We should build out a home screen rather than just having the Bible Screen as the home pages too. I was thinking we could add a simple search there and maybe just a list of bookmarks to start with.

**Comment by cr1pto** [comment]
I think the thing I would like more so than a home screen is the user to go straight to the Bible.  The drawer on the left is available if someone wants to do something special or navigate somewhere.  Maybe this is a good idea for when the user installs the app, maybe like a popup that appears when they first open the app.

**Comment by cr1pto** [comment]
This has actually been completed.
