### ISSUE TITLE
Fix dependabot

### ISSUE THREAD

**Issue by devdave25** [cr1pto/simple_bible#6]
Problem with dependabot on this repo:

```The property '#/updates/0/package-ecosystem' value "" did not match one of the following values: npm, bundler, composer, maven, mix, cargo, gradle, nuget, gomod, docker, elm, gitsubmodule, github-actions, pip, terraform, pub```

**Comment by devdave25** [comment]
I have created a PR for this - https://github.com/cr1pto/simple_bible/pull/8

**Comment by cr1pto** [comment]
This should be closed now.  I believe you can put in your PRs: closes #8 as an example.
